[[hooks]]
name = "go-fmt"
event = "pre-commit"
match = ["*.go"]
command = "go fmt"

[[hooks]]
name = "go-test"
event = "pre-push"
command = "go test ./..."

[[hooks]]
name = "golangci-lint"
event = "pre-commit"
match = ["*.go"]
command = "golangci-lint run --fix --new-from-rev=HEAD"
